name: Code Checks
on: push
jobs:

  test-python-versions:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on:  ${{ matrix.runs-on}}
    continue-on-error: ${{ matrix.allow_failture}}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]
        allow_failture: [false]
        include:
          - python-version: "3.13.0-beta.3"
            allow_failture: true
            runs-on: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: python -m pip install -e .[test]

      - name: Test package
        run: python -m pytest
